# Generated by Django 3.2.7 on 2021-09-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_local_imagem_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='imagem_local',
            new_name='imagem',
        ),
    ]
